version: '3'

volumes:
  pg_data:
  static:
  shared:
    driver: local

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
      - gateway
    volumes:
      - static:/backend_static
      - shared:/shared
  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
  # ds:
  #   build: ./ds/
  #   volumes:
  #     - shared:/shared
  #   depends_on:
  #     - gateway
  task_manager:
    build: ./task_manager/
    env_file: .env
    volumes:
      - shared:/shared
    depends_on:
      - backend