# Generated by Django 4.2.5 on 2023-10-01 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Дата прогноза')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'verbose_name': 'Прогноз магазина',
                'verbose_name_plural': 'Прогнозы магазинов',
            },
        ),
        migrations.CreateModel(
            name='ForecastSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_forecasts.forecast')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Прогноз товара',
                'verbose_name_plural': 'Прогнозы товара',
            },
        ),
        migrations.CreateModel(
            name='ForecastDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('target', models.PositiveIntegerField(verbose_name='Спрос(шт)')),
                ('sales_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_forecasts.forecastsku')),
            ],
            options={
                'verbose_name': 'Ежедневный прогноз',
                'verbose_name_plural': 'Ежедневные прогнозы',
            },
        ),
    ]
