# Generated by Django 4.2.5 on 2023-09-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_forecasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcutegory',
            new_name='subcategory',
        ),
    ]
