# Generated by Django 4.2.5 on 2023-10-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('categories', '0001_initial'),
        ('sales_forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastdaily',
            options={'verbose_name': 'Ежедневный прогноз на товар в ТЦ', 'verbose_name_plural': 'Ежедневные прогнозы на товары в ТЦ'},
        ),
        migrations.AlterField(
            model_name='forecast',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stores.store', to_field='store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='forecastdaily',
            name='sales_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts_daily', to='sales_forecasts.forecastsku', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='forecastsku',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts_sku', to='sales_forecasts.forecast', verbose_name='Прогноз магазина'),
        ),
        migrations.AlterField(
            model_name='forecastsku',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts_sku', to='categories.product', to_field='sku', verbose_name='Продукт'),
        ),
    ]
