# Generated by Django 4.2.5 on 2023-09-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_forecasts', '0002_rename_subcutegory_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sales_forecasts.group', to_field='title', verbose_name='Группа'),
        ),
    ]
