# Generated by Django 4.2.5 on 2023-09-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_forecasts', '0003_alter_category_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='sales_forecasts.category', to_field='title', verbose_name='Категория'),
        ),
    ]
