# Generated by Django 4.2.5 on 2023-09-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_forecasts', '0004_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.SmallIntegerField(default=1, verbose_name='Маркер единицы измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sales_forecasts.subcategory', to_field='title', verbose_name='Подкатегория'),
        ),
    ]
