# Generated by Django 4.2.5 on 2023-09-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('store',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='division',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.SmallIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.city', to_field='city'),
        ),
        migrations.AlterField(
            model_name='store',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.division', to_field='division'),
        ),
        migrations.AlterField(
            model_name='store',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.location', to_field='loc'),
        ),
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.size', to_field='size'),
        ),
        migrations.AlterField(
            model_name='store',
            name='type_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.type_format', to_field='type_format'),
        ),
        migrations.AlterField(
            model_name='type_format',
            name='type_format',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
